eureka:
  client:
    serviceUrl:
     defaultZone: http://localhost:8761/eureka/

server:
  port: 8769


Spring:
  application:
    name: server-zuul
#以/api-a/ 开头的请求都转发给service-ribbon服务；
#以/api-b/开头的请求都转发给service-feign服务；
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: service-ribbon
    api-:
      path: /api-b/**
      serviceId: service-feign